### ISSUE TITLE
Create character bio.html

### ISSUE THREAD

**Issue by JacobBlack1** [MCM1015/PR1_Marvel#4]
Create character bio.html

HTML File - Bio page -

    -Link CSS file 
    -Link script file
    -Use Pure CSS inside of html (https://purecss.io/)
    -code html - use wireframe for reference

**Comment by MCM1015** [comment]
-Function - fetch API

    -Function - Go back button - go back to main page on click

    -Function - pull character name from API - append into character name, pull character image from API - append into html, pull character bio from API - append into html, pull comic list from API - append into html, pull movie list from API, append into html
    
    -Function - play youtube trailer upon selection of movie - pull youtube video from API, append into html
